# Generated by Django 4.0.4 on 2022-05-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdataextending",
            options={
                "verbose_name": "User Data Extension",
                "verbose_name_plural": "User Data Extension",
            },
        ),
    ]
