# Generated by Django 4.0.4 on 2022-05-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="core_tags",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="derived_from",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.tag"
            ),
        ),
    ]
