# Generated by Django 4.0.4 on 2022-05-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_tag_core_tags_tag_derived_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="derived_from",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.tag",
            ),
        ),
    ]
